### ISSUE TITLE
win10下面跑程序不能实现

### ISSUE THREAD

**Issue by Nicolasdeke** [pengcao/chinese_ocr#10]
D:\QQ\chinese_ocr-master\chinese_ocr-master> python pytorch_demo.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "pytorch_demo.py", line 8, in <module>
    import pytorch_model as model
  File "D:\QQ\chinese_ocr-master\chinese_ocr-master\pytorch_model.py", line 12, in <module>
    from ctpn.text_detect import text_detect
  File "D:\QQ\chinese_ocr-master\chinese_ocr-master\ctpn\text_detect.py", line 3, in <module>
    from .ctpn.detectors import TextDetector
  File "D:\QQ\chinese_ocr-master\chinese_ocr-master\ctpn\ctpn\detectors.py", line 10, in <module>
    from ..lib.fast_rcnn.nms_wrapper import nms
  File "D:\QQ\chinese_ocr-master\chinese_ocr-master\ctpn\lib\__init__.py", line 1, in <module>
    from . import fast_rcnn
  File "D:\QQ\chinese_ocr-master\chinese_ocr-master\ctpn\lib\fast_rcnn\__init__.py", line 2, in <module>
    from . import nms_wrapper
  File "D:\QQ\chinese_ocr-master\chinese_ocr-master\ctpn\lib\fast_rcnn\nms_wrapper.py", line 2, in <module>
    from ..utils.cython_nms import nms as cython_nms
  File "D:\QQ\chinese_ocr-master\chinese_ocr-master\ctpn\lib\utils\__init__.py", line 1, in <module>
    from . import bbox
  File "D:\QQ\chinese_ocr-master\chinese_ocr-master\ctpn\lib\utils\bbox.py", line 9
    cimport numpy as np
                ^
SyntaxError: invalid syntax

**Comment by pengcao** [comment]
建议在Ubuntu上跑，Thanks!

**Comment by pengcao** [comment]
建议配置远程Ubuntu的解释器进行调试运行
