### ISSUE TITLE
ImportError: cannot import name 'bbox'

### ISSUE THREAD

**Issue by moFang222** [pengcao/chinese_ocr#3]
运行python demo.py时出现这个错误，怎么解决?

**Comment by pengcao** [comment]
可以把输出的错误贴出来么？

**Comment by zhaochl** [comment]
root@cf164ed04081:/data# python demo.py
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    import ocr
  File "/data/ocr.py", line 10, in <module>
    from ctpn.text_detect import text_detect
  File "/data/ctpn/text_detect.py", line 6, in <module>
    from lib.utils.timer import Timer
  File "/data/ctpn/lib/__init__.py", line 1, in <module>
    from . import fast_rcnn
  File "/data/ctpn/lib/fast_rcnn/__init__.py", line 2, in <module>
    from . import train
  File "/data/ctpn/lib/fast_rcnn/train.py", line 5, in <module>
    from ..roi_data_layer.layer import RoIDataLayer
  File "/data/ctpn/lib/roi_data_layer/__init__.py", line 1, in <module>
    from . import roidb
  File "/data/ctpn/lib/roi_data_layer/roidb.py", line 5, in <module>
    from lib.utils.bbox import bbox_overlaps
  File "/data/ctpn/lib/__init__.py", line 1, in <module>
    from . import fast_rcnn
  File "/data/ctpn/lib/fast_rcnn/__init__.py", line 2, in <module>
    from . import train
  File "/data/ctpn/lib/fast_rcnn/train.py", line 5, in <module>
    from ..roi_data_layer.layer import RoIDataLayer
  File "/data/ctpn/lib/roi_data_layer/__init__.py", line 1, in <module>
    from . import roidb
  File "/data/ctpn/lib/roi_data_layer/roidb.py", line 5, in <module>
    from lib.utils.bbox import bbox_overlaps
  File "/data/ctpn/lib/utils/__init__.py", line 4, in <module>
    from . import bbox
ImportError: cannot import name bbox

**Comment by codeman008** [comment]
I have meet the same problem,have you solve it?

**Comment by Smile-shirley** [comment]
这个问题怎么解决的？
